SQL> 9,SELECT loc,dname
  2  from dept
  3  where deptno = '30';

  SQL> SELECT ENAME,JOB,HIREDATE
  2  FROM EMP
  3  WHERE HIREDATE BETWEEN TO_DATE('1991-02-20','YYYY-MM-DD')
  4  AND TO_DATE('1981-05-01','YYYY-MM-DD')
  5  ORDER BY HIREDATE ASC;

   SELECT
  2  e.NAME,
  3  e.HIREDATE,
  4  NEXT_DAY (ADD_MONTHS(E.HIREDATE,6),'MONDAY')AS REVIEW
  5  FROM EMP e;
  SQL> SELECT e.ENAME, e.DEPTNO
  2  FROM EMP e
  3  WHERE e.SAL = (SELECT MAX(SAL) FROM EMP);
  7,

SQL> SELECT e.ENAME
  2  FROM EMP e
  3  WHERE e.ENAME LIKE '%l%'
  4  AND (e.DEPTNO = 30 OR e.MGR = 7782);

   SELECT e.ENAME, e.DEPTNO
       FROM EMP e
       WHERE e.SAL = (SELECT MAX(SAL) FROM EMP);
    FROM EMP e;
